name: Deploy to EC2

on:
  push:
    branches:
      - main  # Only deploy when this branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@43.204.236.121 << 'EOF'
          cd /var/www/production
          git pull origin main
          npm install
          pm2 restart production
          EOF
