name: Deploy to EC2

on:
  push:
    branches:
      - main  # Only deploy when this branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3  # Stable version
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@43.204.236.121 << 'EOF'
          # Mark the repository directory as safe for git
          git config --global --add safe.directory /var/www/production
          
          # Ensure the correct permissions for the production directory
          sudo chown -R ubuntu:ubuntu /var/www/production
          sudo chmod -R 755 /var/www/production
          
          # Navigate to the project directory
          cd /var/www/production
          
          # Pull the latest code
          git pull origin main
          
          # Install dependencies
          sudo npm install
          
          # Start or restart the PM2 process, ensuring it's named 'production'
          pm2 restart production
          EOF
